name: example
description: A example tus client Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tus_client:
    path: ../
  file_picker: ^1.13.3
  url_launcher: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
