name: tus_client
description: A tus client for dart allowing resumable uploads using the tus protocol.
version: 1.0.2
homepage: https://github.com/jjmutumi/tus_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cross_file: ^0.3.1+4
  http: ^0.13.0
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.3
  build_runner: ^1.11.0