name: tus_client
description: A tus client for dart allowing resumable uploads using the tus protocol.
version: 0.1.1
homepage: https://github.com/jjmutumi/tus_client

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cross_file: ^0.1.0
  http: ^0.12.2
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1